name: Publish
on:
  push:
    tags:
      - v*

jobs:
  github-packages:
    name: Publish Github Packages
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - id: metadata
      name: Get Git Metadata
      uses: WPMedia/git-version-action@v1
    - name: Slack Notify
      if: success()
      uses: ./
      with:
        token: ${{ secrets.SLACK_BOT_TOKEN }}
        payload: '{ "channel": "#publishing-tools-ops", "text": "Build `${{ github.repository }}@${{ steps.metadata.outputs.git_version }}` was successful" }'

